server:
  port: 9091

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AddRequestHeader=X-Gateway, GatewayActive

        - id: inventory-service-route
          uri: lb://inventory-service
          predicates:
            - Path=/api/v1/products/**, /api/v1/instances/**
          filters:
            - AddRequestHeader=X-Gateway, GatewayActive

        - id: menu-service-route
          uri: lb://menu-service
          predicates:
            - Path=/api/v1/plans/**, /api/v1/recipes/**
          filters:
            - AddRequestHeader=X-Gateway, GatewayActive

        - id: history-service-route
          uri: lb://history-service
          predicates:
            - Path=/api/v1/notes/**
          filters:
            - AddRequestHeader=X-Gateway, GatewayActive

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka/